version: '2.9'

services:

  iac-localstack:
    image: localstack/localstack
    container_name: iac-localstack
    hostname: iac-localstack
    healthcheck:
      test: awslocal cloudformation list-stacks
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - SERVICES=cloudformation,eventbridge,lambda,cloudwatch
      - EAGER_SERVICE_LOADING=1
      - LAMBDA_EXECUTOR=local
      - LOCALSTACK_HOSTNAME=0.0.0.0
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - iac-localstack-volume:/tmp/localstack
      - ~/.aws:/root/.aws
    ports:
      - '4566:4566'

volumes:

  iac-localstack-volume:
    driver: local
